# -*- coding: utf-8 -*-
"""Getting the Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gowSfeuhZtcH8wob8K_NgQ7jz1MN2I5r
"""

#pip install yahoofinancials
#pip install yfinance
from yfinance import Ticker
import pandas as pd
from yahoofinancials import YahooFinancials
import requests
from tqdm import tqdm
import time
import pickle

from datetime import datetime, timedelta

#today = datetime.strptime(datetime.today().strftime('%Y-%m-%d'), '%Y-%m-%d')
#yesterday = today - timedelta(days = 1) # Yesterday date as string

def _download_one(ticker, start='2020-06-30', end= datetime.today().strftime('%Y-%m-%d'),
                  auto_adjust=False, back_adjust=False,
                  actions=False, interval="1d", period = None,
                  prepost=False, proxy=None, rounding=False):

    return Ticker(ticker).history(period=period, interval=interval,
                                  start=start, end=end, prepost=prepost,
                                  actions=actions, auto_adjust=auto_adjust,
                                  back_adjust=back_adjust, proxy=proxy,
                                  rounding=rounding, many=True)

# Modify project and reference index according to your needs


tickers_all = []
for project in ["nasdaq"]: ## https://www.nasdaq.com/market-activity/cryptocurrency

    # Load tickers
    companies = pd.read_csv('https://raw.githubusercontent.com/bmarci99/Crypto_trading/main/Data/hi.csv')
    tickers = companies['x'].tolist()
    tickers = [a for a in tickers if a not in tickers_all and "^" not in a and r"/" not in a]
    tickers_all += tickers

    # Download prices
    full_data = {}
    for ticker in tqdm(tickers):
        tckr = _download_one(ticker, actions=True)
        full_data[ticker] = tckr
        
    for i in range(len(full_data)):
        full_data[list(full_data.keys())[i]]['Symbol'] = list(full_data.keys())[i]    
        
    ohlc = pd.concat(full_data.values())
    
    ohlc = ohlc.drop(columns=['Dividends', 'Stock Splits']) ### We wont need these colums


    ohlc.to_csv('Prices.csv')
    print('\ndone with this')

